# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_watchpost_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchpost',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.HomePage'),
        ),
    ]
