# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listenpost',
            old_name='vimeo_id',
            new_name='soundcloud_embed',
        ),
        migrations.AlterField(
            model_name='listenpost',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
