# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('listen', '0002_auto_20170221_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenpost',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.HomePage'),
        ),
    ]
