# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('credits', models.CharField(blank=True, max_length=500, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lookpost',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='lookpost',
            name='vimeo_id',
        ),
        migrations.AddField(
            model_name='lookpost',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='look.LookImage'),
        ),
    ]
