# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0002_auto_20170226_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lookpost',
            name='images',
        ),
        migrations.AddField(
            model_name='lookimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='look.LookPost'),
        ),
    ]
