# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0004_lookimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookimage',
            options={'ordering': ['order']},
        ),
    ]
